### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by blueapple25** [baileyherbert/envato.php#5]
Hello Bailey.........
how are you...

i will install this package in my laravel 5.7 app. So when i run project till the authentication its work good but after redirect url page no any type of response or output get. i just simple print $client variable. but no any output display. please help me if i missing any configuration or other setting.

**Comment by baileyherbert** [comment]
If print isn't showing any output, are you sure the page hasn't encountered a fatal error? You can temporarily set `debug` to true in your `config/app.php` to show errors. You can also try putting simple echo/print statements throughout the page to see where it's failing.
