### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dibbyo456** [baileyherbert/envato.php#8]
```php
$response = $client->catalog->categories(['site' => 'codecanyon.net']);
var_dump($response);
```

Results:

```object(Herbert\Envato\ResultSet)#33 (3) {
  ["results":"Herbert\Envato\ResultSet":private]=>
  NULL
  ["error":"Herbert\Envato\ResultSet":private]=>
  NULL
  ["time":"Herbert\Envato\ResultSet":private]=>
  float(0.63289904594421)

**Comment by baileyherbert** [comment]
The `categories` endpoint only accepts the marketplace name (e.g. `codecanyon`) without the `.net`. Can you give that a try?

I've run into this same issue because they have endpoints which use both conventions.

**Comment by Dibbyo456** [comment]
Yup, now it worked.. You need to fix your ReadMe.md.
I tested with your given example, that's why I was getting error...

I will try to fix the readme examples, there are lots of wrong example..
