### ISSUE TITLE
[Need Help] Correct way to handle TooManyRequestsException

### ISSUE THREAD

**Issue by Dibbyo456** [baileyherbert/envato.php#9]
Hi, so Envato rate limiting me. I wants to correctly handle it.

Envato wrote:

> If you do manage to cross the acceptable number of requests you are permitted to make, you will receive a HTTP 429 response. Included in this response is a HTTP header `Retry-After` that will denote in seconds how long you have to wait until you're able to make requests again.

So, the `Retry-After` header would contain how many seconds I have to wait before I can request again if I'm being rate limited.

1) How can I get the `Retry-After` info?

I'm using a loop, so **instead of throwing a fatal error**, I wants to use `sleep` and continue the loop. 

Sorry, if I'm asking too much.

**Comment by baileyherbert** [comment]
Unfortunately this won't be possible. Back when Envato released their new Build API, it was written in Node.js and Express and running on their own servers. At this point they introduced `Retry-After` and the corresponding headers.

But due to some issues, they moved their API to Amazon AWS and cloud functions, which eliminated the rate limit headers entirely. 

I can't find a copy of the email right now, but I was told by a developer that we should be able to make a "reasonable" amount of requests each second so long as they aren't very big. As a general rule, I limit my own projects to 3 requests per second, or 1 if searching items. I've not run into any issues with rate limiting.

**Comment by Dibbyo456** [comment]
> which eliminated the rate limit headers entirely.

What..!!!! That sucks..! 😢

> 3 requests per second

I was actually doing 5/sec, thank you for the heads up.. ✌

**Comment by baileyherbert** [comment]
Yeah it does. It's been years and they've still yet to update the docs on that or give a fixed limit. 😛 

If you get this exception while performing <= 3/sec, please let me know. I'd love to write up some notes on this later. FYI - last I checked the rate limiting was per-token, not per IP, but this could have changed.

**Comment by Dibbyo456** [comment]
I hate the v3 API specially the rate limiting. For the last 2 years I've been using the legacy API, which had no rate limiting, but they've now rate limited it to [3 requests per minute](https://forums.envato.com/t/rate-limiting-on-the-legacy-api/188055). So now I'm forced to use the v3 API. 😡

> last I checked the rate limiting was per-token, not per IP

No, it's actually mixed. They rate limit IP as well as Tokens. 😕

They really needs to update their API docs. 😒

**Comment by Dibbyo456** [comment]
@baileyherbert Hello, need a little help. I'm very new in PHP. I've never used `try-catch` before, but I wants to learn it. After stackoverflow-ing for a while, I came up with this:

```php
try {
    $response = $client->catalog->item(['idxxxx' => "19659555"]);
} catch ( BadRequestException $e ) {
    echo "caught..!";
   //do stuff.
}
```
I've used `idxxxx` on purpose, so I can produce the `BadRequestError`. But the problem is my php codes not catching the `BadRequestException` instead it's throwing the `Fatal Error`:

> Fatal error: Uncaught Herbert\Envato\Exceptions\BadRequestException in C:\wamp64\www\project55\includes\vendor\baileyherbert\envato\src\Envato\Endpoint.php:102 Stack trace: #0 C:\wamp64\www\project55\includes\vendor\baileyherbert\envato\src\Envato\Endpoint.php(61): Herbert\Envato\Endpoint->perform('/v3/market/cata...', Array) #1 C:\wamp64\www\project55\new\new1.php(9): Herbert\Envato\Endpoint->__call('item', Array) #2 {main} thrown in C:\wamp64\www\project55\includes\vendor\baileyherbert\envato\src\Envato\Endpoint.php on line 102

My coding is probably wrong, like I said, I'm very new in `try-catch` thing, can you please tell me how to properly catch the error and do stuff?

**Comment by baileyherbert** [comment]
Did you import the `BadRequestException` at the top of your file? e.g.

```php
use Herbert\Envato\Exceptions\BadRequestException;
```

**Comment by Dibbyo456** [comment]
Oh. No, I did not. I didn't know I need to include the `BadRequestException` class. 🙃
Now, it's working fine. 👌

So, I need to include all the exception class one by one?
Can't I simply include all?

**Comment by baileyherbert** [comment]
You could alternatively specify the full path as you have been doing:

```php
try {
    $response = $client->catalog->item(['idxxxx' => "19659555"]);
} 
catch ( Herbert\Envato\Exceptions\BadRequestException $e ) {
    echo "caught..!";
   //do stuff.
}
```

**Comment by Dibbyo456** [comment]
Hi, sorry for again bothering you.

> But due to some issues, they moved their API to Amazon AWS and cloud functions, which eliminated the rate limit headers entirely.

After your this statement, I rated-limited myself again on purpose, just to make sure whether are not the `Retry-After` header are actually gone. Looks like it's not gone, they `Retry-After` header still exists...! 😃

![Screenshot 1](https://s.put.re/iivYkCc9.png)

**Comment by baileyherbert** [comment]
😱 

Thank you for pointing that out. Guess they're a bit more active with bug fixes than I give them credit for. 

If I get a chance tomorrow, I'm going to try and release a rewrite of this library (`v3.0`) which will include support for that header and will be more organized overall.

**Comment by Dibbyo456** [comment]
Hahaha... Guess it's a good thing that I was skeptical about it.... 😜

Well, It would be awesome if we have a **Auto-Retry** function built-in (optional of course)..
```php
sleep('Retry-After'+1); //+1 for make sure the time correctly passes.
```
What do you think? 🤔

**Comment by baileyherbert** [comment]
I think it's a good idea and that I'll definitely make it happen. I've been wanting to rewrite this library along with my Node.js library to have the same sensible API, and both can benefit from such a thing. 😄

**Comment by baileyherbert** [comment]
Hi @Dibbyo456,

Well, I won't be able to finish the new client today. I'll just push an update to this version which will be able to grab that header. What do you think of putting it in the exception itself?

```php
try {
    $response = $client->catalog->item(['idxxxx' => "19659555"]);
} catch (Herbert\Envato\Exceptions\BadRequestException $e) {
    $seconds = $e->getSecondsRemaining(); // int
    $e->wait(); // sleep until time is up
}
```

**Comment by Dibbyo456** [comment]
That would get the job done. 🤞

**Comment by baileyherbert** [comment]
Well, I've published a branch (rate-limiting) to mess with it. I'm actually not able to trigger the rate limit for some reason... I've tried my best without performing a full scale DDoS but they just won't give me a 429. 🤣 

If you'd like to try and test it out, that'd be a great help:

- Branch: https://github.com/baileyherbert/envato.php/tree/rate-limiting
- Code example: https://github.com/baileyherbert/envato.php/tree/rate-limiting#rate-limiting

**Comment by Dibbyo456** [comment]
> I'm actually not able to trigger the rate limit for some reason...

Lookup single item (50-100 items) ( `$client->catalog->item(['id' => 12345]);` ) with 20 parallel request and loop them, you will definitely hit 429. 😁

> If you'd like to try and test it out, that'd be a great help.

Sure.! 😃

**Comment by Dibbyo456** [comment]
Helllo, I just tired the new rate-limiting branch, and it's **working perfectly**.. 😍

![](https://s.put.re/C4PjNiZ9.png)

----

> I'm actually not able to trigger the rate limit for some reason... I've tried my best without performing a full scale DDoS but they just won't give me a 429.

I wrote a little script, where you can easily produce the 429 error. You can [download it from here](https://s.put.re/Y4J5t2YL.zip).

Just replace `token_goes_here` with your actual token, then run the script. You will definitely hit 429.
I hope this helps. 😊

**Comment by Dibbyo456** [comment]
Hello,
Are you planning to merge it to master or planning to release v3 with altogether?

**Comment by baileyherbert** [comment]
Sorry for the inactivity. I've now merged it and pushed to Composer. v3.0 won't be happening for a while since I didn't get it done this week. I keep underestimating it, but one of the ideas behind v3.0 is having objects for each type of response from the Envato API which is a lot of work. Will continue working on it as I have time of course! 😄
